### ISSUE TITLE
[Feat]: Creating search bar for contributer page

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#404] opened 2023-05-20 10:05 UTC
### What feature?

It will make this website more attractive if a search system  present in the contributor page to search a specific user between thousands of contributors.

Please assign this task to me @priyankarpal 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by balaji-sivasakthi** [comment] 2023-05-20 12:08
I would like to work on this feature under GSSOC'23.

**Comment by priyankarpal** [comment] 2023-05-21 08:51
Duplicate of #400

**Closed by priyankarpal** 2023-05-21 08:51 UTC
Labels: duplicate, ⭐ goal: addition, ✨ goal: improvement, gssoc23

**Comment by noobtuber20103152** [comment] 2023-05-23 13:28
issue no #400 is for creating a search bar for project by my issue is to make a search bar for contributor page not project to find an user from thousand of users. @priyankarpal

**Comment by priyankarpal** [comment] 2023-05-23 13:32
will it help us?
