### ISSUE TITLE
Feat: Typewriter Animation 

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1021] opened 2023-05-31 03:57 UTC
### Add screenshots

<img width="960" alt="2023-05-31" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/99a1c7e6-459b-4a0d-953f-8c846185e8cf">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-05-31 04:13
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/790

**Closed by priyankarpal** 2023-05-31 04:13 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
