### ISSUE TITLE
Feat: ADDING A FEEDBACK SECTION

### ISSUE THREAD

**Issue by kharshita590** [priyankarpal/ProjectsHut#1078] opened 2023-06-02 16:28 UTC
### What feature?

I WANT TO ADD A FEEDBACK SECTION

### Add screenshots

I WILL ADD THE FILE AND YOU CAN USE THAT WHEREVER YOU WANT

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-06-02 16:54
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/752

**Closed by priyankarpal** 2023-06-02 16:54 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
