### ISSUE TITLE
[style]: On hover effect on the links in the navbar

### ISSUE THREAD

**Issue by akash19coder** [priyankarpal/ProjectsHut#575] opened 2023-05-22 06:56 UTC
### What's the style idea?

We need to add a hover effect on the links on the navbar.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-22 08:09
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/373.

**Closed by priyankarpal** 2023-05-22 08:09 UTC
Labels: 👯‍♂️ style, 🚦status: awaiting triage
