### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by warisamir** [priyankarpal/ProjectsHut#416] opened 2023-05-20 12:03 UTC
### what's wrong in the documentation?

We need to update this image with the new as these line in between is hindrance and making difficult to see through it 
![image](https://github.com/priyankarpal/ProjectsHut/assets/77074869/64f7f2d3-64e2-42ce-9435-db7568c828da)
the black forming the grid

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/77074869/4c1fa9c4-7814-4a65-8b9c-ba79330baa38)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by balaji-sivasakthi** [comment] 2023-05-20 13:23
I would like to work on this under GSSOC'23. please assign it to me.

**Comment by warisamir** [comment] 2023-05-20 13:55
I would like to work on this issue please assign me the role

**Comment by priyankarpal** [comment] 2023-05-21 08:58
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333

**Closed by priyankarpal** 2023-05-21 08:58 UTC
Labels: 📚 Documentation, 🕵🏼‍♂️ goal: Improvement

**Comment by priyankarpal** [comment] 2023-05-21 08:59
> I would like to work on this under GSSOC'23. please assign it to me.

@balaji-sivasakthi don't do spam on every issue we will assign the person who will create the issue if he/she wants to work otherwise we will assign someone who will want to work

**Comment by warisamir** [comment] 2023-05-21 12:06
i cant be able to see the deployed version of the app 
![image](https://github.com/priyankarpal/ProjectsHut/assets/77074869/7fd82149-064d-4f1a-9634-71d393eafe66)
i cant make changes without seeing it
