### ISSUE TITLE
[style]: Scaling of contributor's profile image

### ISSUE THREAD

**Issue by DivyanshiNarang** [priyankarpal/ProjectsHut#789] opened 2023-05-25 10:19 UTC
### What's the style idea?

*We can improve the styling of Contributors page by adding a hovering effect like scaling of their profile image.*

**Please assign this issue to me under Gssoc'23** @priyankarpal 

### Add screenshots

<img width="882" alt="Screenshot 2023-05-25 153556" src="https://github.com/priyankarpal/ProjectsHut/assets/74779601/b06b6317-ff26-4a4c-82b9-bab1f532c7a7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-25 11:12
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/699

**Closed by priyankarpal** 2023-05-25 11:12 UTC
Labels: 👯‍♂️ style, 🚦status: awaiting triage
