### ISSUE TITLE
[style]: footer alignment 

### ISSUE THREAD

**Issue by rushabhpanbude** [priyankarpal/ProjectsHut#515] opened 2023-05-21 13:42 UTC
### What's the style idea?

We need to improve  
footer alignment 

### Add screenshots

Before 
<img width="1440" alt="Screenshot 2023-05-21 at 6 57 40 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/63780356/dc79a374-09bd-4834-839e-c5468ca4acd7">
After

<img width="1439" alt="Screenshot 2023-05-21 at 6 54 07 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/63780356/73afa9b9-28f1-4318-898e-381fb8d07d2c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 20:25
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/504

**Closed** 2023-05-22 08:44 UTC
Labels: 🗿duplicate, 👯‍♂️ style, 🚦status: awaiting triage
