### ISSUE TITLE
chore: project addition by Ayan-Joshi

### ISSUE THREAD

**Issue by ayan-joshi** [priyankarpal/ProjectsHut#2212] opened 2023-10-08 18:40 UTC
### Add a new project to the list

I want to add a new project Sorting Visualizer , 
Assign me this issue so I can start my work @priyankarpal 

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-10-08 18:41
duplicate of #2211

**Closed by priyankarpal** 2023-10-08 18:41 UTC
Labels: good first issue, 🟩 priority: low, 🚦status: awaiting triage, projects addition
