### ISSUE TITLE
[Bug]:  projects page - Sort project based on technology is not working

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#385] opened 2023-05-20 04:13 UTC
### What happened?

I found a BUG 🐞

in project section sort project based on technology feature is not working 

when you click on - react js, node js  ............. python  
is not working 

i want to work on this issue

### Add screenshots

Add screenshots
![Screenshot (91)](https://github.com/priyankarpal/ProjectsHut/assets/119125519/462f490f-4215-4ea4-8f3e-d0ae928b377f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mandliyarajendra11** [comment] 2023-05-20 04:13
can you assign me this issue

**Comment by creator79** [comment] 2023-05-20 07:31
@priyankarpal I would like to work on this issue under gssoc'23 can you assign me this issue

**Comment by harmeetsingh11** [comment] 2023-05-20 15:37
Hi! I am a GSSoC Contributor. Please assign it to me. Already made changes in local repository.

**Comment by Jyotipal29** [comment] 2023-05-20 17:34
I would like to work on this issue. With my skills and experience, I am confident in resolving this issue effectively. Please assign it to me

**Comment by crocmons** [comment] 2023-05-20 18:21
I would like to work on this project as a GSSoC'23 contributor. Please assign it to me! I have already worked on similar projects like this I just need to add sort functionalities and it will be completed.

**Comment by priyankarpal** [comment] 2023-05-21 08:43
Duplicate of #370 also, got fixed

**Closed by priyankarpal** 2023-05-21 08:43 UTC
Labels: 🐞 bug, ✌️priority: high
