### ISSUE TITLE
[Bug]: "Add Your Projects" Button Broken

### ISSUE THREAD

**Issue by itsOmSarraf** [priyankarpal/ProjectsHut#508] opened 2023-05-21 13:16 UTC
### What happened?

I found a BUG 🐞,

"Add Your Projects" button gives a 404 error, whereas the "Docs" on Navbar redirects to a page which has mentioned the steps.

Attached Screenshot(s) below. 

If you want I can make make a new webpage in JavaScript and Tailwind with the guide , or just link the button. 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/83817663/ec37449d-d305-4e13-b152-d8d33ebdfdf6)

![image](https://github.com/priyankarpal/ProjectsHut/assets/83817663/56bdaac0-a3d9-4e68-9291-96549d1e3d40)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 13:20
duplicate of #484

**Closed by priyankarpal** 2023-05-21 13:20 UTC
Labels: 🐞 bug, 🙃 duplicate, ✌️priority: high
