### ISSUE TITLE
docs page designing

### ISSUE THREAD

**Issue by gaur15** [priyankarpal/ProjectsHut#381] opened 2023-05-20 02:46 UTC
### What's the style idea?

We need to improve  the page by first removing the lines which are showing in middle and top pages and after that using css to make it look attractive 

### Add screenshots

Add screenshots
<img width="805" alt="Screenshot 2023-05-20 081514" src="https://github.com/priyankarpal/ProjectsHut/assets/133087361/203c00b5-2c6d-4159-9300-b742b49c0516">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mani200307** [comment] 2023-05-20 02:51
I would like to work on this under GSSOC'23. Could you please assign me this?

**Comment by Keshav-0907** [comment] 2023-05-20 05:03
Can I please Work on this issue?

**Comment by priyankarpal** [comment] 2023-05-21 08:40
> ### What's the style idea?
> We need to improve the page by first removing the lines which are showing in middle and top pages and after that using css to make it look attractive
> 
> ### Add screenshots
> Add screenshots <img alt="Screenshot 2023-05-20 081514" width="805" src="https://user-images.githubusercontent.com/133087361/239663935-203c00b5-2c6d-4159-9300-b742b49c0516.png">
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

could you share the demo?
also we are using tailwind css

**Comment by priyankarpal** [comment] 2023-05-21 12:35
also it's a duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333

**Closed by priyankarpal** 2023-05-21 12:35 UTC
Labels: 🕵🏼‍♂️ goal: Improvement, 👯‍♂️ style, 🚦status: awaiting triage
