### ISSUE TITLE
Active State For Nav Links 

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1893] opened 2023-07-30 04:51 UTC
### What feature?

Currently the nav links only have hover state but when we click on it and it open the respective link, but we can no longer see it highlighted to make the user aware on which page he is.

### Add screenshots

![IMG_20230730_102032](https://github.com/priyankarpal/ProjectsHut/assets/89072785/560ede2a-61b2-4fbd-8014-fa6808f2b056)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-07-30 05:14
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1887 

please check existing issues first

**Closed by priyankarpal** 2023-07-30 05:14 UTC
Labels: duplicate, ⭐ goal: addition

**Comment by Souravvmishra** [comment] 2023-07-30 05:17
Apologies Brother, I tried searching but I guess I missed that.
