### ISSUE TITLE
[style]: 

### ISSUE THREAD

**Issue by iqrasarwar** [priyankarpal/ProjectsHut#1979] opened 2023-08-06 13:11 UTC
### What's the style idea?

I want to add light/day mode to the website.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-08-06 15:13
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1840

**Closed by priyankarpal** 2023-08-06 15:13 UTC
Labels: ✨ goal: improvement, 🚦status: awaiting triage, 🕹 aspect: interface
