### ISSUE TITLE
improvement in header section 

### ISSUE THREAD

**Issue by gaur15** [priyankarpal/ProjectsHut#1203] opened 2023-06-14 04:43 UTC
### What feature?

shifting logo towards left and dark theme towards right to make it look more appealing 

### Add screenshots

<img width="960" alt="Screenshot 2023-06-14 101040" src="https://github.com/priyankarpal/ProjectsHut/assets/133087361/28a221ee-1fa7-4ac5-b31a-520a5413d74b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-06-14 13:20
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1161

**Closed by priyankarpal** 2023-06-14 13:20 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
