### ISSUE TITLE
[style]: 

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#577] opened 2023-05-22 07:52 UTC
### What's the style idea?

We need to improve  On hover effect on navbar

### Add screenshots

No effect on hover

<img width="960" alt="2023-05-22" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/86c2c620-584e-4409-8f96-9189902548b2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-22 08:07
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/373. please try to check the existing issues first

**Closed by priyankarpal** 2023-05-22 08:07 UTC
Labels: 🗿duplicate, 👯‍♂️ style
