### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RoshanAnsy** [priyankarpal/ProjectsHut#538] opened 2023-05-21 18:14 UTC
### What happened?

document page is not loading on the small screen and gets a 404 error.

### Add screenshots

![Screenshot 2023-05-21 234143](https://github.com/priyankarpal/ProjectsHut/assets/91673102/1cccdbde-b74c-4d37-879e-468b12b413c9)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 18:19
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/484

**Closed by priyankarpal** 2023-05-21 18:19 UTC
Labels: 🐞 bug, ✌️priority: high, 🚦status: awaiting triage
