### ISSUE TITLE
feat:Light and Dark theme in navbar

### ISSUE THREAD

**Issue by SHARMA-1729** [priyankarpal/ProjectsHut#1955] opened 2023-08-04 04:48 UTC
### What feature?

I wll add light and dark theme in navbar.

### Add screenshots

![theme](https://github.com/priyankarpal/ProjectsHut/assets/129518514/23786ee9-9015-4824-b922-e2cebdcd7a3a)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-08-05 08:16
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1840

**Closed by priyankarpal** 2023-08-05 08:16 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
