### ISSUE TITLE
[Feature]: Add Simple Filter Section in Projects Section[Different With Others]

### ISSUE THREAD

**Issue by NarendraKoya999** [priyankarpal/ProjectsHut#1202] opened 2023-06-14 04:39 UTC
### Issue Description:
- **Add Simple Filter Section with Simple Sections [ Already Suggested One Person]. But, I designed with different that.**

### What that Feature Looks Like According to Our Current and Future Project Design Card UI's
> Filters By

   - ` Languages ` **( In Languages Section, Who is Calling "This is A Language". Only that Languages Put in this Section)**
   - `Tools ` **(In Tools Section, Who is Calling "This is A Tool". Only that Tools Put in this Section)**
   - `Most Liked`  **(In Projects Section, Lot of Projects are there. So, "Which Repository has Most Liked" that Shows in 
                              ascending to Descending Order )**
   - `Most Recent`  **(In Project Section, "Which Projects are Most Recently Added". That Projects are Shows on Webpage )**

### Screenshot of My Feature Request

<img width="843" alt="projectshut-2" src="https://github.com/priyankarpal/ProjectsHut/assets/84512164/5d828a34-ac93-4b5f-9a52-0c72e76eb8ef">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-06-14 05:02
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1047

**Closed by priyankarpal** 2023-06-14 05:02 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
