### ISSUE TITLE
Translate README file into हिंदी language

### ISSUE THREAD

**Issue by sabhisharma-ise** [priyankarpal/ProjectsHut#451] opened 2023-05-20 18:35 UTC
Issue: The README file is currently available in only a few langauges. This makes it difficult for Hindi speakers to learn about the project and how to use it.

Solution: We propose to translate the README file into Hindi. This will make it easier for Hindi speakers to learn about the project and how to use it.

Benefits: Translating the README file into Hindi will make the project more accessible to Hindi speakers. This will help to increase the project's reach and impact.

I hope this helps!

Contributor  - Sabhi Sharma (GSSOC'23)

**Comment by priyankarpal** [comment] 2023-05-20 18:46
Duplicate of #429 so I'm closing this one

**Closed by priyankarpal** 2023-05-20 18:46 UTC
