### ISSUE TITLE
data: project addition by prrockzed

### ISSUE THREAD

**Issue by prrockzed** [priyankarpal/ProjectsHut#705] opened 2023-05-24 06:19 UTC
### Add a new project to the list

 I want to add a new project to the list 
This is a 3D project named Haunted House. Fun project made using Three.js library in Javascript. It is an immersive and interactive experience that takes the user in a spooky atmospheric environment. It is not just an animation or a gif. It is a small world, where the user can go through the entire environment using their mouse.

Through the use of dynamic movement of ghostly character, details on the walls and doors of the house brings the haunted house project to life. Also with so many grave around and some spirited lights moving around the house in an eerie way intensifies the atmosphere.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-26 11:01
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/788

**Closed by priyankarpal** 2023-05-26 11:01 UTC
Labels: 👍  status: approved, gssoc23, 🌱 chore: projects addition, level1

**Comment by prrockzed** [comment] 2023-05-26 11:31
@priyankarpal ig this is not a duplicate of #788. It was a rubik's cube game. This is a haunted house project made using three.js library. A 3D project(not like other 2D websites) where user can navigate around the canvas.
Please check into this.
