### ISSUE TITLE
[style]: Improve the header footer and doc page

### ISSUE THREAD

**Issue by sumitkr2000** [priyankarpal/ProjectsHut#430] opened 2023-05-20 14:03 UTC
### What's the style idea?

Hey @priyankarpal I wantto improve the header footer and doc page of the website. The doc page is not looking good. Please assign me this issue/ Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 09:17
footer: Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/378
docs: https://github.com/priyankarpal/ProjectsHut/issues/333
navbar: https://github.com/priyankarpal/ProjectsHut/issues/373

**Closed by priyankarpal** 2023-05-21 09:17 UTC
Labels: 🙃 duplicate, 🕵🏼‍♂️ goal: Improvement, 👯‍♂️ style
