### ISSUE TITLE
[Feat]: search bar for projects

### ISSUE THREAD

**Issue by 007xylogramori** [priyankarpal/ProjectsHut#408] opened 2023-05-20 10:47 UTC
### What feature?

we can implement a search feature to search among the available projects.

the search will be based on what you type in the search box and then only projects will be visible that matches the search text

### Add screenshots

![Screenshot (129)](https://github.com/priyankarpal/ProjectsHut/assets/119863801/f8a8453f-866d-4723-9ba4-88e62f556f84)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment] 2023-05-20 11:06
Hey @007xylogramori ### I have already created this issue

**Comment by ashishsurya** [comment] 2023-05-20 11:50
i can contribute to this issue, please assign to me

**Comment by priyankarpal** [comment] 2023-05-21 03:33
Duplicate of #400

**Closed by priyankarpal** 2023-05-21 03:33 UTC
Labels: 🦾 Feature, 🕵🏼‍♂️ goal: Improvement
