### ISSUE TITLE
[style]: Light dark toggle button to toggle switch

### ISSUE THREAD

**Issue by KawishAli6578** [priyankarpal/ProjectsHut#422] opened 2023-05-20 13:10 UTC
### What's the style idea?

We can improve our toggle button to toggle switch which can look much better and we can keep our toggle button on mobile ui 
I would like to work on it under gssoc23.

### Add screenshots

![dark](https://github.com/priyankarpal/ProjectsHut/assets/95257675/d039791a-6d2f-46b0-a125-883e54dea186)
for dark mode
![light](https://github.com/priyankarpal/ProjectsHut/assets/95257675/b86660d2-8adf-4832-b9e8-19e92260c3b5)
for light mode 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Shubham185y** [comment] 2023-05-20 13:15
Assign this to me i can do this

**Comment by adityavpawar** [comment] 2023-05-20 19:48
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by priyankarpal** [comment] 2023-05-21 09:07
Duplicate of #376

**Comment by KawishAli6578** [comment] 2023-05-22 14:37
hey @priyankarpal I would like to add that this toggle button does not clarify its purpose as long as someone clicks on it 
![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/faa41f7b-dc83-4766-9b00-0b5504bbb36e)
we can make it look more prominent by improving its ui so users can easily identify this toggle button's purpose
![](https://user-images.githubusercontent.com/95257675/239689207-b86660d2-8adf-4832-b9e8-19e92260c3b5.PNG)
![](https://user-images.githubusercontent.com/95257675/239689200-d039791a-6d2f-46b0-a125-883e54dea186.PNG)
we can use the icon as i show in images or mabe you can provide if you have any better design icon

**Comment by KawishAli6578** [comment] 2023-05-23 10:05
hey @priyankarpal can you tell in   `git commit -m "feat/docs/fix: :emoji-name: <EXPLAIN-YOUR_CHANGES>"`
what does feat/docs/fix: :emoji-name: means?

**Comment by priyankarpal** [comment] 2023-05-23 10:15
> hey @priyankarpal can you tell in `git commit -m "feat/docs/fix: :emoji-name: <EXPLAIN-YOUR_CHANGES>"` what does feat/docs/fix: :emoji-name: means?

if your fixed a feature then it will be `git commit -m "feat: fixed this feature"` if docs then `git commit -m "docs: improved readme"` etc like this. you need to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). `:emoji-name` mean you need to add emoji name to show emojis here. you can remove `:emoji-name`

**Closed** 2023-05-23 12:37 UTC
Labels: 🕵🏼‍♂️ goal: Improvement, 👍  status: approved, 👯‍♂️ style, gssoc23, 🟦 level 2
