### ISSUE TITLE
Add some hover effect on Navbar links update dark/light mode icon not visible when dark mode is turn on. 

### ISSUE THREAD

**Issue by Geeta259** [priyankarpal/ProjectsHut#406] opened 2023-05-20 10:19 UTC
### What's the style idea?

We need to improve  Navbar links by adding some minimal hover effect on it. When dark mode on not visible to user. 
Docs section can be modified by providing each steps in a beginner friendly way by adding each commands images step wise.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by masif2002** [comment] 2023-05-20 12:00
Hey, I'm a GSSoC '23 contributor, and would like to work on this

**Comment by masif2002** [comment] 2023-05-20 12:04
@priyankarpal can I have it assigned?

**Comment by claddyk** [comment] 2023-05-20 13:41
@Geeta259 I've reproduced the issue and will be able to solve this. Can I be assigned this?

**Comment by priyankarpal** [comment] 2023-05-21 08:56
> ### What's the style idea?
> We need to improve Navbar links by adding some minimal hover effect on it. When dark mode on not visible to user. Docs section can be modified by providing each steps in a beginner friendly way by adding each commands images step wise.
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333
& https://github.com/priyankarpal/ProjectsHut/issues/373

**Closed by priyankarpal** 2023-05-21 08:56 UTC
Labels: duplicate, ✨ goal: improvement, gssoc23
