### ISSUE TITLE
[Feat]: Add Project Metrics and Analytics to User Profiles

### ISSUE THREAD

**Issue by drakshi** [priyankarpal/ProjectsHut#889] opened 2023-05-27 06:37 UTC
### What feature?

I would like to suggest the implementation of project metrics and analytics on user profiles. This enhancement would allow developers to access valuable information regarding their projects' performance and impact. Key metrics such as views, downloads, contributions, and other relevant data extracted from GitHub profiles would be displayed on the user profile page.

**Implementation Details:**
To implement this feature:

Integration with GitHub API: Integrate with the GitHub API to retrieve and display project metrics and analytics on user profiles, ensuring accurate and up-to-date information.

User-Friendly Design: Design the user profile page to present project metrics and analytics in a clear and visually appealing manner, making it easy for developers to interpret and utilize the data.

Performance Optimization: Implement efficient data retrieval and processing methods to ensure minimal impact on platform performance when loading and displaying project metrics.

By adding project metrics and analytics to user profiles, ProjectsHut can empower developers with valuable insights and create a more informed and engaged community.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-27 09:39
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/411 

we will add a graph of contributions in the projectshut of the users.

**Closed by priyankarpal** 2023-05-27 09:39 UTC
Labels: 🦾 Feature
