### ISSUE TITLE
[Bug]: Scroll to Top not visible under 'Built for collaboration' at bottom

### ISSUE THREAD

**Issue by hemant14050** [priyankarpal/ProjectsHut#779] opened 2023-05-25 05:48 UTC
### What happened?

I'm in GSSOC'23.
Scroll to the bottom of the page.
Locate the "Built for collaboration" section.
Observe that the "Scroll to Top" button is not visible within this section.
And also bg-color is not suitable in footer for this button

### Add screenshots

Add screenshots
"Built for collaboration" section
![bug-scroll-to-top](https://github.com/priyankarpal/ProjectsHut/assets/112842857/181bac34-426a-4bab-8753-6e9448a10a53)

"Footer" section
![bug-scroll-to-top-color](https://github.com/priyankarpal/ProjectsHut/assets/112842857/fd0f453c-4171-4cf6-a1e9-5267ad4f360d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-25 05:51
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/715

**Closed by priyankarpal** 2023-05-25 05:51 UTC
Labels: 🐞 bug, 🚦status: awaiting triage
