### ISSUE TITLE
feat: Enhancing Profile Sharing with Social Media Links

### ISSUE THREAD

**Issue by Akanksha-202** [priyankarpal/ProjectsHut#1976] opened 2023-08-06 06:05 UTC
### What feature?

Allowing users to share profiles through various social media platforms like Facebook, Twitter, WhatsApp, LinkedIn, etc. in addition to the existing option of copying the profile link to the clipboard.

### Add screenshots

Sample work:
![Screenshot 2023-08-02 124706](https://github.com/priyankarpal/ProjectsHut/assets/100708686/528c8995-9803-479c-afb4-8f8b149230be)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-08-06 19:07
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1809

**Closed by priyankarpal** 2023-08-06 19:07 UTC
Labels: duplicate, ⭐ goal: addition
