### ISSUE TITLE
[Bug]: document page is not loading on the small screen and gets a 404 error.

### ISSUE THREAD

**Issue by RoshanAnsy** [priyankarpal/ProjectsHut#539] opened 2023-05-21 18:18 UTC
### What happened?

I am getting errors on the small screen on the document page.
  

### Add screenshots

![Screenshot 2023-05-21 234143](https://github.com/priyankarpal/ProjectsHut/assets/91673102/0abf3daf-e226-4c87-b0aa-247e731debb5)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 18:23
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/484

**Closed by priyankarpal** 2023-05-21 18:23 UTC
Labels: 🐞 bug, ✌️priority: high, 🚦status: awaiting triage
