### ISSUE TITLE
In docs, PR section appear twice

### ISSUE THREAD

**Issue by ShivamAgarwal00** [priyankarpal/ProjectsHut#380] opened 2023-05-20 02:46 UTC
### Bug

In Docs, Create Pull Request and and wait for merge section appear twice in a web page.

### Add screenshots

![screenshot](https://github.com/priyankarpal/ProjectsHut/assets/124357186/57b7e429-c251-4bd7-beea-b58db017aee8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

I want to contribute for this issue as in gssoc'23

**Comment by Naincy04** [comment] 2023-05-20 05:23
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by priyankarpal** [comment] 2023-05-21 12:36
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333

we are working on it

**Closed by priyankarpal** 2023-05-21 12:36 UTC
Labels: 🐞 bug, ✌️priority: high
