### ISSUE TITLE
[Feat]: Footer Section can be updated more

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [priyankarpal/ProjectsHut#439] opened 2023-05-20 16:29 UTC
### What feature?

We can improve footer like giving proper copyright protected along with that in footer section lot more info are there but present web there is nothing like that.

Please Allow me to contribute for updation of this section under GSSoC '23 (as a contributor). 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yuvraj6446** [comment] 2023-05-20 16:44
- We can implement an upward arrow(navigator) which will navigate towards the top of the page.
- We can add contact information and social media links
-We can add about section which will tell the information about the site.
-Awards, Certifications, or Affiliations: If your business has received any industry awards, certifications, or affiliations, you can showcase them in the footer to build credibility and trust.
-Frequently Asked Questions (FAQs): Summarize a few frequently asked questions and answers relevant to your business or website, providing quick assistance to visitors.

**Comment by Rupantar-Borphukan** [comment] 2023-05-20 18:04
> * We can implement an upward arrow(navigator) which will navigate towards the top of the page.
> * We can add contact information and social media links
>   -We can add about section which will tell the information about the site.
>   -Awards, Certifications, or Affiliations: If your business has received any industry awards, certifications, or affiliations, you can showcase them in the footer to build credibility and trust.
>   -Frequently Asked Questions (FAQs): Summarize a few frequently asked questions and answers relevant to your business or website, providing quick assistance to visitors.

Yes we can do that.
Assign me this issue so that I can solve that problem.

**Comment by adityavpawar** [comment] 2023-05-20 19:47
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by priyankarpal** [comment] 2023-05-21 09:14
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/378

**Closed by priyankarpal** 2023-05-21 09:14 UTC
Labels: 🦾 Feature, 🕵🏼‍♂️ goal: Improvement
