### ISSUE TITLE
[Feat]: Authentication feature in the website.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [priyankarpal/ProjectsHut#764] opened 2023-05-24 18:15 UTC
### What feature?

I have an idea to add authentication by using firebase. I want to work on it under GSSoC'23.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-24 18:17
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/364

**Closed by priyankarpal** 2023-05-24 18:17 UTC
Labels: 🦾 Feature, 🚦status: awaiting triage
