### ISSUE TITLE
[Feat]: Add a form to add projects directly from the website rather than manually creating a fork

### ISSUE THREAD

**Issue by kunalkashyap-1** [priyankarpal/ProjectsHut#741] opened 2023-05-24 14:05 UTC
### What feature?

I have an idea to enhance the data entry process by either making a modal on projects page or making a entirely different page (do tell me which one you would prefer), which reduces the manual labour of entire process by simply giving a form through which people can enter their data in projects.json.
I'm in GSSOC'23.

Do assign me this issue if you like the idea.

The image gives a rough idea of how the flow would potentially be...

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/91254500/447b3e24-943c-4991-8e0c-e1a701660846)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-24 14:46
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/672

**Closed by priyankarpal** 2023-05-24 14:46 UTC
Labels: 🦾 Feature, 🚦status: awaiting triage
