### ISSUE TITLE
[style]: Redesign Docs Page

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [priyankarpal/ProjectsHut#456] opened 2023-05-20 21:08 UTC
### What's the style idea?

Redesigning the Docs Page will be better so as to make it eye-catching.
I would like to redesign this !! 
Plz Assign me this Issue !!
I am a GSSOC'23 Contributor.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-21 12:39
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333

**Closed by priyankarpal** 2023-05-21 12:39 UTC
Labels: 🙃 duplicate, 🕵🏼‍♂️ goal: Improvement, 👯‍♂️ style
