### ISSUE TITLE
[style]: Box Shadows instead of borders ⚡

### ISSUE THREAD

**Issue by apneduniya** [priyankarpal/ProjectsHut#405] opened 2023-05-20 10:13 UTC
### What's the style idea?

We need to modernish the project's cards a bit by adding BOX SHADOWS instead of borders which will make it look more appealing as well as it will help to differentiate in components. Not only in that but we can also add in buttons and other components too ⚡.

I want to contribute this for you ❤️.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/113763427/fe6b6048-03c2-4e38-8b12-3e0b277764e6)
![image](https://github.com/priyankarpal/ProjectsHut/assets/113763427/6246dcb7-1942-405c-ad64-913a9983d467)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Sameep002** [comment] 2023-05-20 10:25
Hello, i can work on this issue. I have experience in ReactJs and Tailwind CSS!!

**Comment by apneduniya** [comment] 2023-05-20 10:29
> Hello, i can work on this issue. I have experience in ReactJs and Tailwind CSS!!

I am too here to contribute to this issue :)

**Comment by Sameep002** [comment] 2023-05-20 10:34
> > Hello, i can work on this issue. I have experience in ReactJs and Tailwind CSS!!
> 
> I am too here to contribute to this issue :)

But only mentors can create issues right? 🤔

**Comment by priyankarpal** [comment] 2023-05-21 08:53
Duplicate of  #368

**Closed by priyankarpal** 2023-05-21 08:53 UTC
Labels: duplicate, ✨ goal: improvement, gssoc23
