### ISSUE TITLE
feat: Adding dark to light Theme Switching feature

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [priyankarpal/ProjectsHut#1863] opened 2023-07-27 15:20 UTC
### What feature?

To enhace the UI and user experience I would like to add the Theme Switcher to the website. It would help enhance UX and would be a greate addition to the modern design of the website.

For now I have attached a sample design for switching button as a refernce.
Upon assigning I would add theme switching support for the entire website.

Please do assign me.
Thanks❤

### Add screenshots

#These are just for reference of the possible designs, I will make the final design once assigned.

![image](https://github.com/priyankarpal/ProjectsHut/assets/97378312/a11265ca-ecfc-4f92-85c2-ea9b8d5a52dd)

![image](https://github.com/priyankarpal/ProjectsHut/assets/97378312/54dc269c-714b-4c5f-8222-14e7bdd4c0a2)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment] 2023-07-29 10:09
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1840

**Closed by priyankarpal** 2023-07-29 10:09 UTC
Labels: ⭐ goal: addition, 🚦status: awaiting triage
