### ISSUE TITLE
Hover effect on buttons [Bug]: 

### ISSUE THREAD

**Issue by Guli93** [priyankarpal/ProjectsHut#565] opened 2023-05-22 04:44 UTC
### What happened?

I found a BUG 🐞There is no hover effect on home page button .

please assign this issue to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-22 07:55
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/373

**Closed by priyankarpal** 2023-05-22 07:55 UTC
Labels: 🐞 bug, 🗿duplicate
