### ISSUE TITLE
[Bug]: home page Images going outside the screen  

### ISSUE THREAD

**Issue by Ironspider42** [priyankarpal/ProjectsHut#972] opened 2023-05-29 10:30 UTC
### What happened?

I found a BUG 🐞
Hi @priyankarpal 
The images are not align correctly in a smaller window size, it goes outside the screen.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/74675824/94232df1-b5b9-4795-a75e-616fad56a593

If it is a bug then i want to work upon this
Please assign me the task under GSSoC'23.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-05-29 18:33
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/625

**Closed by priyankarpal** 2023-05-29 18:33 UTC
Labels: 🛠 goal: fix, 🚦status: awaiting triage
